name: quality

on:
  schedule:
    - cron: '42 0 * * 1'
  push:
  pull_request:
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: true

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        IDENTITY: [ emojisearch, iconsearch, logosearch, supertinyicons ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sh unidecode pyaml

      - name: Validate ${{ matrix.IDENTITY }} repos
        run: ./bin/validate_repo.py --input=data/${{ matrix.IDENTITY }}.yaml

