name: release

on:
  schedule:
    - cron: '42 0 * * 1'
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        IDENTITY: [ emojisearch, iconsearch, logosearch, supertinyicons ]

    steps:
      - uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sh unidecode pyaml

      - name: Configure git
        run: |
          git config --global init.defaultBranch main

      - name: Build index for github repos
        run: ./bin/build-index.sh ${{ matrix.IDENTITY }} github

      - name: Build index for gitlab repos
        if: ${{ matrix.IDENTITY != 'supertinyicons' && matrix.IDENTITY != 'emojisearch' }}
        run: ./bin/build-index.sh ${{ matrix.IDENTITY }} gitlab

      - name: Build download file
        if: ${{ matrix.IDENTITY != 'supertinyicons' }}
        run: ./bin/build-download.sh ${{ matrix.IDENTITY }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: ignore
          name: release-artifacts-${{ matrix.IDENTITY }}
          path: |
            build/download-${{ matrix.IDENTITY }}.tgz
            build/index-${{ matrix.IDENTITY }}-github.tgz
            build/index-${{ matrix.IDENTITY }}-gitlab.tgz
          retention-days: 1


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: List downloaded files
        run: ls -lR

      - name: Set release info
        run: |
          echo "RELEASE_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          echo "RELEASE_TAG=$(date -u +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            release-artifacts-emojisearch/download-emojisearch.tgz
            release-artifacts-emojisearch/index-emojisearch-github.tgz
            release-artifacts-iconsearch/download-iconsearch.tgz
            release-artifacts-iconsearch/index-iconsearch-github.tgz
            release-artifacts-iconsearch/index-iconsearch-gitlab.tgz
            release-artifacts-logosearch/download-logosearch.tgz
            release-artifacts-logosearch/index-logosearch-github.tgz
            release-artifacts-logosearch/index-logosearch-gitlab.tgz
            release-artifacts-supertinyicons/index-supertinyicons-github.tgz
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_DATE }}
          body: |
            Automatically created on ${{ env.RELEASE_DATE }}
          draft: false
          prerelease: false
