name: release

on:
  schedule:
    - cron: '42 0 * * 1'
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sh unidecode pyaml

      - name: Build Github Icon Index
        run: ./bin/build-index.sh icons github

      - name: Build Gitlab Icon Index
        run: ./bin/build-index.sh icons gitlab

      - name: Build Icons Download
        run: ./bin/build-download.sh icons

      - name: Build Github Logo Index
        run: ./bin/build-index.sh logos github

      - name: Build Gitlab Logo Index
        run: ./bin/build-index.sh logos gitlab

      - name: Build Logos Download
        run: ./bin/build-download.sh logos

      - name: Set release info
        run: |
          echo "RELEASE_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          echo "RELEASE_TAG=$(date -u +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/download-icons.tgz
            build/index-icons-github.tgz
            build/index-icons-gitlab.tgz
            build/download-logos.tgz
            build/index-logos-github.tgz
            build/index-logos-gitlab.tgz
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_DATE }}
          body: |
            Automatically created on ${{ env.RELEASE_DATE }}
          draft: false
          prerelease: false
